export const workflowTaskProto = {
    "wrk_id": 2,
    "list_title": "we",
    "wrk_pos": 1,
    "wrk_old_pos": 1,
    "ar_sec": 0,
    "legoId": 0,
    "color": "#fafafa",
    "children": [
        {
            "workFlowId":0,
            "legoId":0,
            "steps":"",
            "responsibility":"",
            "comments":"",
            "linkDoc":"",
            "position":1,
            "parent_id":2,
            "t_createdby":0,
            "t_created_date":"",
            "label":"#c8ced3",
            "startdate":"",
            "enddate":"",
            "_status":0,
            "completedby":0,
            "completeddate":null,
            "complete_per":0,
            "priority":0,
            "wrk_id":null,
            "list_title":"",
            "wrk_pos":1,
            "wrk_old_pos":1,
            "ar_sec":0,
            "color":"#27b6ba",
            "expand_status_st":1
            ,"commentsCount":0,
            "documentsCount":0,
            "taskCount":0,
            "t_createdby_name":"",
            "s_createdby_name":"",
            "responsibilities":[],
            "checkList":[],
            "commentsList":[],
            "isAutoCompletePer":0,
            "iseditable":false,
            "isnew":false,
            "color_list":[{"name":"#ddd"}]
        }
    ],
    'activetasks': 0,
    "t_createdby_name": "",
    "expand_status": true,
    "iseditable": false,
    "isnew": false,
    "isBoardTask": 0,
    "isAutoCompletePer": 0,
};
export const workflowSubTaskProto = {
    "workFlowId": 1,
    "legoId": 0,
    "steps": "",
    "responsibility": "",
    "comments": "",
    "linkDoc": "",
    "position": 1,
    "parent_id": 2,
    "t_createdby": 0,
    "t_created_date": "",
    "label": "#c8ced3",
    "startdate": "",
    "enddate": "",
    "_status": 0,
    "completedby": 0,
    "completeddate": null,
    "complete_per": 0,
    "priority": 4,
    "wrk_id": null,
    "list_title": "",
    "wrk_pos": 1,
    "wrk_old_pos": 1,
    "ar_sec": 0,
    "color": "#27b6ba",
    "expand_status_st": 1,
    "commentsCount": 0,
    "documentsCount": 0,
    "taskCount": 0,
    "t_createdby_name": "",
    "s_createdby_name": "",
    "responsibilities": [],
    "checkList": [],
    "commentsList": [],
    "isAutoCompletePer": 0,
    "iseditable": false,
    "isnew": false,
    "color_list": [{ 'name': '#ddd' }]
};
export const workflowCheckListProto = {
    'employeeId': 0,
    'companyId': 0,
    'task_chkid': 0,
    'taskid': 0,
    'chkname': '',
    'status': 0,
    'createdby': 0,
    'datetime': '',
    'completedby': 0,
    'completeddate': '',
    'completeby_name': 0,
    'createdby_name': 0,
    'position': 0,
    'old_position': 0,
    'options': 0
}
export const boardListProto = {
    selectedBoard: 0,
    companyId: 0,
    b_id: 0,
    board_title: "",
    legoid: 0,
    position: 0,
    Archieve_Section: 0,
    UserName: "",
    isnew: true,
    iseditable: true,
}